/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/assets/models/tableCrossCloth.glb -o components/TableCrossCloth.tsx -t -s -r public 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_tableCrossCloth: THREE.Mesh
    Mesh_tableCrossCloth_1: THREE.Mesh
  }
  materials: {
    wood: THREE.MeshStandardMaterial
    carpet: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/assets/models/tableCrossCloth.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.42}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh_tableCrossCloth.geometry} material={materials.wood} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_tableCrossCloth_1.geometry} material={materials.carpet} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/tableCrossCloth.glb')
